### ISSUE TITLE
Build fails regardless of whether servant is installed from master or not

### ISSUE THREAD

**Issue by moodmosaic** [arealities/simplestore#1]
Steps to Reproduce:

``` bash
$ git clone git@github.com:arealities/simplestore.git
$ cd simplestore
$ git clone git@github.com:haskell-servant/servant.git
$ cabal sandbox add-source servant/servant
$ cabal install --only-dependencies
$ cabal build
```

A possible workaround has been reported [here](https://twitter.com/ToJans/status/647781781245153280).

**Comment by ToJans** [comment]
FYI you were really close; you just had to add `cabal sandbox add-source servant/servant-server`

**Comment by moodmosaic** [comment]
OMG! That was it O.o Thanks for pointing that out!
